---
title: "Zadanie 2"
author: "Bartosz Mikulski"
date: "11 11 2020"
output:
  html_document: default
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = "")
```

```{r, warning=FALSE, message=FALSE}
library(ggplot2)
```

## Punkt 1 

```{r p1, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(depth)) + 
  geom_histogram() +
  labs(title="Histogram zmiennej depth")
```

## Punkt 2 

```{r p2, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(depth)) + 
  geom_histogram(binwidth = 0.2) +
  labs(
    title="Histogram zmiennej depth",
    subtitle="Z szerokością kubełka 0.2"
    )
```

## Punkt 3

```{r p3, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(depth)) + 
  geom_histogram(binwidth = 0.2) + 
  xlim(c(55, 70)) +
  labs(
    title="Histogram zmiennej depth",
    subtitle="Z szerokością kubełka 0.2 oraz ograniczeniem przedziału osi x do [55,70]"
    )
```

## Punkt 4

```{r p4_1, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(depth, color=cut, fill=cut)) + 
  geom_histogram(binwidth = 0.2, alpha=0.75) + 
  xlim(c(55, 70)) +
  labs(
    title="Histogram zmiennej depth",
    subtitle="Zmienna cut decyduje o kolorze"
  )
```

```{r p4_2, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(depth)) + 
  geom_histogram(binwidth = 0.2) + 
  xlim(c(55, 70)) + 
  facet_wrap(~cut) +
  labs(
    title="Histogram zmiennej depth",
    subtitle="Zmienna cut decyduje o panelu"
  )
```

## Punkt 5 

```{r p5_1, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(price)) + 
  geom_histogram() +
  labs(
    title="Histogram zmiennej price"
  )
```

```{r p5_2, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(price)) + 
  geom_histogram(binwidth = 150) +
  labs(
    title="Histogram zmiennej price",
    subtitle="Z szerokością kubełka 150"
  )
```

```{r p5_3, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(price)) + 
  geom_histogram(binwidth = 150) + 
  xlim(c(0, 10000)) +
  labs(
    title="Histogram zmiennej price",
    subtitle="Z szerokością kubełka 150 oraz ograniczeniem przedziału osi x do [0,10000]"
  )
```

```{r p5_4, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(price, color=cut, fill=cut)) + 
  geom_histogram(binwidth = 150, alpha=0.75) + 
  xlim(c(0, 10000)) +
  labs(
    title="Histogram zmiennej price",
    subtitle="Zmienna cut decyduje o kolorze"
  )
```

```{r p5_5, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(price)) + 
  geom_histogram(binwidth = 150) + 
  xlim(c(0, 10000)) +
  facet_wrap(~cut) +
  labs(
    title="Histogram zmiennej price",
    subtitle="Zmienna cut decyduje o panelu"
  )
```

## Punkt 6

```{r p6, warning=FALSE, message=FALSE}
ggplot(diamonds, aes(carat, price)) + 
  geom_point(alpha=0.1) +
  labs(title="Relacja między zmiennymi carat i price")
```
